services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - npm_network
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - portainer-data:/data
    environment:
      DOCKER_HOST: tcp://docker-socket-proxy:2375
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  npm_network:
    external: true

volumes:
  portainer-data: